### ISSUE TITLE
Plotly Tutorial

### ISSUE THREAD

**Issue by chuangyu-hscy** [chuangyu-hscy/ubiquitous-goggles#1]
Plotly tutorial by Derek Banas

Video link: https://www.youtube.com/watch?v=GGL6U0k8WYA

**TODO**
- [ ] [00:00](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=0s) Intro
- [ ] [00:14](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=14s) What is Plotly?
- [ ] [00:38](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=38s) Installation
- [ ] [01:51](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=111s) Imports
- [ ] [03:49](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=229s) Basics
- [ ] [05:41](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=341s) Line Plots
- [ ] [06:19](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=379s) Built-in Datasets
- [ ] [07:41](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=461s) Multiple Plots
- [ ] [09:04](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=544s) Styling Plots
- [ ] [12:01](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=721s) Style Grids
- [ ] [17:45](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=1065s) Query Data
- [ ] [26:07](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=1567s) Scatter Plots
- [ ] [32:43](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=1963s) Pie Charts
- [ ] [34:27](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=2067s) Colormaps
- [ ] [39:45](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=2385s) Histograms
- [ ] [44:28](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=2668s) Box Plots
- [ ] [52:30](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=3150s) Violin Plots
- [ ] [58:12](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=3492s) Density Heatmap
- [ ] [1:01:30](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=3690s) 3D Scatter Plots
- [ ] [1:02:48](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=3768s) 3D Line Plots
- [ ] [1:03:35](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=3815s) Scatter Matrix
- [ ] [1:04:21](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=3861s) Map Scatter Plot
- [ ] [1:06:38](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=3998s) Choropleth Maps
- [ ] [1:09:17](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=4157s) Polar Chart
- [ ] [1:11:50](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=4310s) Ternary Plot
- [ ] [1:13:24](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=4404s) Facets
- [ ] [1:18:17](https://www.youtube.com/watch?v=GGL6U0k8WYA&t=4697s) Animated Plots
